### ISSUE TITLE
My Singing Monsters wiki has not migrated to wiki.gg

### ISSUE THREAD

**Issue by Poopooracoocoo** [alex4401/wikigg-redirect-extension#17]
**Describe the bug**
https://mysingingmonsters.wiki.gg/wiki/My_Singing_Monsters_Wiki Site is not found 

**To Reproduce**
1. Search for "my singing monsters wiki" on Google
2. Click on redirected wiki.gg result 

**Expected behavior**
Do not redirect

**Additional info:**
- Browser [e.g. chrome, safari] Chrome 116
- Wiki [e.g. Temtem, ARK, Sea of Thieves] N/A

**Comment by alex4401** [comment]
Discord one is in the wiki.gg server. Also attaching a screenshot from my browser history (from around last extension update).
![image](https://github.com/alex4401/wikigg-redirect-extension/assets/33527044/b186d9ff-c20e-43cd-ba0f-69eab1dd8103)
![image](https://github.com/alex4401/wikigg-redirect-extension/assets/33527044/4c0cd35f-fb13-4218-9269-6fbbe65bbff7)

**Comment by alex4401** [comment]
Builds submitted. Chrome and Firefox should be alright in a few hours max, Edge may take up to a week (or more).
